logo = '''                                                                                                                                                                                                                         
                                                                                                                                                             bbbbbbbb                                                    
        GGGGGGGGGGGGG                                                                                                                                        b::::::b                                                    
     GGG::::::::::::G                                                                                                                                        b::::::b                                                    
   GG:::::::::::::::G                                                                                                                                        b::::::b                                                    
  G:::::GGGGGGGG::::G                                                                                                                                         b:::::b                                                    
 G:::::G       GGGGGGuuuuuu    uuuuuu      eeeeeeeeeeee        ssssssssss       ssssssssss        nnnn  nnnnnnnn    uuuuuu    uuuuuu     mmmmmmm    mmmmmmm   b:::::bbbbbbbbb        eeeeeeeeeeee    rrrrr   rrrrrrrrr   
G:::::G              u::::u    u::::u    ee::::::::::::ee    ss::::::::::s    ss::::::::::s       n:::nn::::::::nn  u::::u    u::::u   mm:::::::m  m:::::::mm b::::::::::::::bb    ee::::::::::::ee  r::::rrr:::::::::r  
G:::::G              u::::u    u::::u   e::::::eeeee:::::eess:::::::::::::s ss:::::::::::::s      n::::::::::::::nn u::::u    u::::u  m::::::::::mm::::::::::mb::::::::::::::::b  e::::::eeeee:::::eer:::::::::::::::::r 
G:::::G    GGGGGGGGGGu::::u    u::::u  e::::::e     e:::::es::::::ssss:::::ss::::::ssss:::::s     nn:::::::::::::::nu::::u    u::::u  m::::::::::::::::::::::mb:::::bbbbb:::::::be::::::e     e:::::err::::::rrrrr::::::r
G:::::G    G::::::::Gu::::u    u::::u  e:::::::eeeee::::::e s:::::s  ssssss  s:::::s  ssssss        n:::::nnnn:::::nu::::u    u::::u  m:::::mmm::::::mmm:::::mb:::::b    b::::::be:::::::eeeee::::::e r:::::r     r:::::r
G:::::G    GGGGG::::Gu::::u    u::::u  e:::::::::::::::::e    s::::::s         s::::::s             n::::n    n::::nu::::u    u::::u  m::::m   m::::m   m::::mb:::::b     b:::::be:::::::::::::::::e  r:::::r     rrrrrrr
G:::::G        G::::Gu::::u    u::::u  e::::::eeeeeeeeeee        s::::::s         s::::::s          n::::n    n::::nu::::u    u::::u  m::::m   m::::m   m::::mb:::::b     b:::::be::::::eeeeeeeeeee   r:::::r            
 G:::::G       G::::Gu:::::uuuu:::::u  e:::::::e           ssssss   s:::::s ssssss   s:::::s        n::::n    n::::nu:::::uuuu:::::u  m::::m   m::::m   m::::mb:::::b     b:::::be:::::::e            r:::::r            
  G:::::GGGGGGGG::::Gu:::::::::::::::uue::::::::e          s:::::ssss::::::ss:::::ssss::::::s       n::::n    n::::nu:::::::::::::::uum::::m   m::::m   m::::mb:::::bbbbbb::::::be::::::::e           r:::::r            
   GG:::::::::::::::G u:::::::::::::::u e::::::::eeeeeeee  s::::::::::::::s s::::::::::::::s        n::::n    n::::n u:::::::::::::::um::::m   m::::m   m::::mb::::::::::::::::b  e::::::::eeeeeeee   r:::::r            
     GGG::::::GGG:::G  uu::::::::uu:::u  ee:::::::::::::e   s:::::::::::ss   s:::::::::::ss         n::::n    n::::n  uu::::::::uu:::um::::m   m::::m   m::::mb:::::::::::::::b    ee:::::::::::::e   r:::::r            
        GGGGGG   GGGG    uuuuuuuu  uuuu    eeeeeeeeeeeeee    sssssssssss      sssssssssss           nnnnnn    nnnnnn    uuuuuuuu  uuuummmmmm   mmmmmm   mmmmmmbbbbbbbbbbbbbbbb       eeeeeeeeeeeeee   rrrrrrr            
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         
                                                                                                                                                                                                                         '''